# docker-compose.yml
version: '3.8'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm start
    networks:
      - frontend
networks:
  frontend:
    driver: bridge
